# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kana < Formula
  desc "A simple, portable CLI for efficient WordPress development."
  homepage "https://github.com/ChrisWiegman/kana"
  version "0.24.5"
  license "GPL-3.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisWiegman/kana/releases/download/0.24.5/kana_macos_x86_64.zip"
      sha256 "3bf83b73548c8c4eacd1931d2db53003b79b13481ed6cf8b509a5dd88792ffb6"

      def install
        bin.install "kana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisWiegman/kana/releases/download/0.24.5/kana_macos_arm64.zip"
      sha256 "85e538b7ac5621011e9efb1fbbad9662235eb4bc9714f8185a6a52ce5b28c3be"

      def install
        bin.install "kana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChrisWiegman/kana/releases/download/0.24.5/kana_linux_x86_64.zip"
        sha256 "14dbe16fec9840312da5a1a2860009d357f95b82420734fe39737c13c4609d2b"

        def install
          bin.install "kana"
        end
      end
    end
  end

  test do
    system "#{bin}/kana version"
  end
end
