# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kana < Formula
  desc "A simple, portable CLI for efficient WordPress development."
  homepage "https://github.com/ChrisWiegman/kana"
  version "0.24.2"
  license "GPL-3.0 license"

  on_macos do
    on_intel do
      url "https://github.com/ChrisWiegman/kana/releases/download/0.24.2/kana_macos_x86_64.zip"
      sha256 "82aacbc8aafcd63c426415e355c800c41d5d7823b7a721a0e69247c664ff0be1"

      def install
        bin.install "kana"
      end
    end
    on_arm do
      url "https://github.com/ChrisWiegman/kana/releases/download/0.24.2/kana_macos_arm64.zip"
      sha256 "f6962908184c51a29f1c07b65b114472ca74f55a74d7154fcc6f019d3bcb9935"

      def install
        bin.install "kana"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ChrisWiegman/kana/releases/download/0.24.2/kana_linux_x86_64.zip"
        sha256 "f68dd4cd709abe44462f6a23c97c7b4f12a0706e5052bbe655a1be5594a79789"

        def install
          bin.install "kana"
        end
      end
    end
  end

  test do
    system "#{bin}/kana version"
  end
end
